# Generated by Django 5.0 on 2023-12-08 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth_app', '0002_mm'),
    ]

    operations = [
        migrations.DeleteModel(
            name='mm',
        ),
    ]
